### ISSUE TITLE
Contatto

### ISSUE THREAD

**Issue by lorenzocorallo** [salvatore-abello/argofamiglia#1]
Ciao, vorrei avere un tuo contatto se possibile per utilizzare questa repo (Telegram, Instagram, Discord, ...).

**Comment by salvatore-abello** [comment]
> Ciao, vorrei avere un tuo contatto se possibile per utilizzare questa repo (Telegram, Instagram, Discord, ...).

Puoi contattarmi su Discord: **salvatore.abello#8649**
