### ISSUE TITLE
Correct installation procedure and functions

### ISSUE THREAD

**Issue by lmarceg** [salvatore-abello/argofamiglia#2]
Hi,
I wanted to test your software as my kid will go to a new school in September and they use ArgoFamiglia.
I have Debian 10 with Python 3.7, so the first method you propose is not working for me (I should download and compile a new Python version, and for now I wanted to skip this part). Therefore I opted for the second option,` python3 -m pip install argofamiglia` but I see a different set of files being downloaded.
Especially argofamiglia.py is completely different across the two versions and I wonder which one of the two is the correct one (of if both are correct, I don't know).

I also struggle to use the various options, because in the argofamiglia.py I see in github, I can just recognzie the `getCompitiByDate()`, but what about all the other functions I would need, like getting notes, marks, absences, notifications and so on? How should I structure my python?

If instead I look at the files I have, I see a kind of list of functions

```
"""
modes: all: params: _dc
docenticlasse --> docenti della classe
bachecanuova --> comunicazioni bacheca
votigiornalieri --> voti
compiti --> compiti
argomenti --> argomenti
verifica --> per testare
login --> login:
schede --> informazioni personali
votigiornalieri --> voti giornalieri
notedisciplinari --> note
assenze --> assenze
orario --> orario
oggi --> Lista di voti, compiti, assenze, etc...
periodiclasse --> scrutinio
votiscrutinio --> voti scrutinio
presavisionebachecanuova --> presa visione di un documento in bacheca:
    params: {'presaVisione': presaVisione, 'prgMessaggio': id}
"""

```
but I don't know how to call them and also which parameters to pass

Can you please help?
Thanks!
Luca

**Comment by lmarceg** [comment]
Solved. I upgraded my python to 3.8 and installed argofam9iglia with the first method and not the second.
Will play with it when school starts, however session.dashboard() seems to provide the entire json output

**Comment by salvatore-abello** [comment]
> Solved. I upgraded my python to 3.8 and installed argofam9iglia with the first method and not the second. Will play with it when school starts, however session.dashboard() seems to provide the entire json output

That's not a wrapper problem, but how they implemented the API.
